#!/usr/bin/env python2.7
"""We're built so as to allow an implementation-specific wrapper around general 
functionality. The former needs to be able get the path of the general 
functionality. This script is meant to be within scope of the latter to call.
"""

import sys
import os.path

# This is for any situation where we're not properly install, when we wouldn't 
# be able to find ourselves via the path.
root_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, root_path)

# However, that path will be no good if the scripts have been properly 
# installed to the correct system executable paths. We'll actually have to 
# import to get the correct path.

import sapi
official_path = os.path.abspath(os.path.join(os.path.dirname(sapi.__file__), '..'))
print(official_path)
