#!/usr/bin/env python2.7

import sys
import os.path
root_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, root_path)

import os.path
import sapi
sapi_path = os.path.abspath(os.path.join(os.path.dirname(sapi.__file__), '..'))

import os
os.chdir(sapi_path)

import subprocess
cmd = ['gunicorn', '-c', 'sapi/resources/gunicorn.conf.prod', 'sapi.wsgi:wsgi']
p = subprocess.Popen(cmd)
r = p.wait()
if r != 0:
    raise EnvironmentError("Gunicorn launch failed.")
